# Site settings
title: ProSayJ
SEOTitle: 杨健的技术博客
header-img: img/home-bg.jpg
email: ProSayJ@gmail.com
description: "关于一些~~~~"
keyword: "ProSayJ, Spring, SpringBoot, 杨健的技术博客"
url: "https://weibo.com/yangjian"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

post:
  author: yangjian